version: 2.1
orbs:
  node: circleci/node@5
jobs:
  deploy:
    executor: node/default
    working_directory: ~/big-whoop
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "SHA256:URTfidP7xVnBRdhWO03zsI0UdDd1nk+ht5pqT1f4UcY"
      - run:
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
            ssh $SSH_USER@$SSH_HOST "rm -dRf /home/mgimeno/apps/big-whoop"
            ssh $SSH_USER@$SSH_HOST "mkdir -p /home/mgimeno/apps/big-whoop"
            scp -rv ./website/* $SSH_USER@$SSH_HOST:apps/big-whoop
workflows:
  deploy:
    jobs:
      - deploy
